<a href="https://colab.research.google.com/github/fc63/gender-classification/blob/main/g_blogs/g_blogs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I converted the https://u.cs.biu.ac.il/~koppel/BlogCorpus.htm dataset from xml format to dataframe format and saved it as pickle.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import zipfile

zip_path = "/content/drive/MyDrive/blogsgender/blogs.zip"
extract_path = "/content/blogs"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [3]:
import os
import pandas as pd
import xml.etree.ElementTree as ET

from bs4 import BeautifulSoup

data = []
folder_path = "/content/blogs/blogs"

for filename in os.listdir(folder_path):
    if not filename.endswith(".xml"):
        continue

    parts = filename.rsplit(".", 5)
    if len(parts) != 6:
        continue

    user_id, gender, age, industry, sign, _ = parts
    file_path = os.path.join(folder_path, filename)

    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            soup = BeautifulSoup(f.read(), 'html.parser')
            posts = soup.find_all("post")

            for post in posts:
                raw_text = post.get_text(strip=True)
                if raw_text:
                    data.append({
                        "text": raw_text,
                        "gender": gender
                    })

    except Exception as e:
        print(f"Yine hata ({filename}):", e)

df = pd.DataFrame(data)
print("Toplam satır:", len(df))
df.head()

Toplam satır: 676626

                                                text gender
0  It's getting COLD!!!! what the hell is going o...   male
1  Hey I know its a little late, but I just found...   male
2  fourthling (11:06:39 PM): You've gone monosyll...   male
3  Well, I'm an idiot!  But a reasonably happy on...   male
4  Well...I thought I would make one post before ...   male

In [4]:
df

                                                     text  gender
0       It's getting COLD!!!! what the hell is going o...    male
1       Hey I know its a little late, but I just found...    male
2       fourthling (11:06:39 PM): You've gone monosyll...    male
3       Well, I'm an idiot!  But a reasonably happy on...    male
4       Well...I thought I would make one post before ...    male
...                                                   ...     ...
676621  mood: omg listening to: ...  me and sharons ho...  female
676622  mood:tired listening to: the air con buzzing  ...  female
676623  mood: stressed!! listening to: someday by nick...  female
676624  mood: tired listening to: heal the world-micha...  female
676625  mood: - listening to: the windchime tinkling  ...  female

[676626 rows x 2 columns]

Warning: total number of rows (676626) exceeds max_rows (20000). Limiting to first (20000) rows.

In [5]:
df['gender'].value_counts()

gender
male      343066
female    333560
Name: count, dtype: int64

In [6]:
import pickle

output_path = "/content/drive/MyDrive/datasets/blogs_gender_df.pkl"

with open(output_path, "wb") as f:
    pickle.dump(df, f)